name: Publish Transport Data

on:
  workflow_dispatch:  # Ручной запуск
  schedule:
    - cron: '0 16 * * 1-5'  # 19:00 МСК, только рабочие дни

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout data repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Create timetable.json
      run: |
        python create_timetable.py
        
    - name: Show published data
      run: |
        echo "=== Published files ==="
        ls -la data/
        echo "=== Timetable metadata ==="
        python -c "import json; data=json.load(open('data/timetable.json')); print(f'Version: {data[\"metadata\"][\"version\"]}'); print(f'Generated: {data[\"metadata\"][\"generated_at\"]}'); print(f'Transport types: {list(data[\"data\"].keys())}')"
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Auto-update transport data $(date +'%Y-%m-%d %H:%M')" || exit 0
        git push
